service: thefort-comz-bot
provider:
  name   : aws
  runtime: nodejs12.x
  region : us-east-1
  role   : arn:aws:iam::034383583207:role/thefort-comz-bot-role
  timeout: 5
  stage  : ${opt:stage, 'dev'}
  memorySize: 128
functions:
  dispatcher:
    handler    : bot.run
    description: Comz Bot Backend
    environment:
      BOT_NAME        : ${self:custom.botName}
      VERIFICATION_TOKEN: ${ssm:slack_verification_token~true}
      BOT_TOKEN         : ${ssm:slack_bot_token~true}
    exclude: 
      - package-lock.json
    optimize: true
    # Create the API gateway
    events:
      - http:
          path: "/event-handler"
          method: post
custom:
  botName: comzbot
